version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/resource_db
    depends_on:
      - mongodb
volumes:
  mongo_data:
